version: "3"
services:
  fashion-ec_web:
    container_name: fashion-ec_web
    build: ./docker/web
    ports:
      - "8080:80"
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - fashion-ec_app

  fashion-ec_app:
    container_name: fashion-ec_app
    build: ./docker/app
    volumes:
      - ./src:/var/www/src
    working_dir: /var/www/src
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=fashion-ec_db
      - DB_PORT=3306
      - DB_DATABASE=fashion-ec_db
      - DB_USERNAME=phper
      - DB_PASSWORD=secret

    depends_on:
      - fashion-ec_db

  fashion-ec_db:
    container_name: fashion-ec_db
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=fashion-ec_db
      - MYSQL_USER=phper
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
